---
title: "gnscript"
output: html_document
---

# this script is used to produce the figures contained in the paper, Christensen, R. C. (2020). Elite professionals in transnational tax governance. Global Networks. DOI: 10.1111/glob.12269.

library(tidyverse)
library(TraMineR)
library(cluster)

# this script uses a 'df' data object in a long format, with three columns ('no','year','code'), containing, respectively, information about the career sequence identifier, the year of the career, and the coding (sequence state).

# defining colour palettes based on expertise and sector

cpalp <- c("white", "#fdae61","#abdda4","#abdda4","#abdda4","#ffffbf","#ffffbf","#ffffbf","black","black","black","lightgrey","#d7191c","#d7191c","#d7191c","#2b83ba","#2b83ba","#2b83ba") # expertise

cpalr <- c("white", "khaki4", "#8dd3c7", "#bebada", "#ffffb3", "#8dd3c7", "#bebada", "#ffffb3", "#8dd3c7", "#bebada", "#ffffb3", "lightgrey", "#8dd3c7", "#bebada", "#ffffb3", "#8dd3c7", "#bebada", "#ffffb3") # sector

# figure 1

df %>% 
  ggplot() +
  geom_tile(aes(x=year,y=no,fill=code),colour="#F8F8F8") + 
  theme_void() +
  theme(
    axis.text.y = element_text(face = "plain", size = 5, margin=margin(0,-20,0,0)),
    axis.text.x = element_text(face = "plain", size = 8, margin=margin(10,0,-10,0),angle=269),
    legend.position="bottom",
    legend.margin=margin(0,0,20,0)) +
  scale_y_continuous(breaks=1:98) +
  scale_x_continuous(position="top",breaks=1964:2014) +
  scale_fill_manual(values=cpalp,guide="none")

# figure 2

df %>% 
  ggplot() +
  geom_tile(aes(x=year,y=no,fill=code),colour="#F8F8F8") + 
  theme_void() +
  theme(
    axis.text.y = element_text(face = "plain", size = 5, margin=margin(0,-20,0,0)),
    axis.text.x = element_text(face = "plain", size = 8, margin=margin(10,0,-10,0),angle=269),
    legend.position="bottom",
    legend.margin=margin(0,0,20,0)) +
  scale_y_continuous(breaks=1:98) +
  scale_x_continuous(position="top",breaks=1964:2014) +
  scale_fill_manual(values=cpalr,guide="none")
  
## generating clusters with optimal matching

## calculating sequence distances
## using only the most recent 30 years of careers (for visual interpretation and comparability)
## with indel cost set to half the mean of the substitution costs, cf. MacIndoe and Abbott 2004
## using transition rates (TRATE) for substitution costs

distances = df %>% 
  filter(year %in% 1985:2014) %>% 
  pivot_wider(id_cols = "no", names_from = "year", values_from = "code") %>% 
  seqdef() %>% 
  seqdist(method = "OM", indel = 0.93, sm = "TRATE") 

## cutting into clusters with Ward's method, and a k = 4 cluster solution (tested for conceptual meaning and agglomerative coefficient)

clusterward <- agnes(distances, diss = TRUE, method = "ward")

cluster4 <- cutree(clusterward, k = 4)

## plotting

df$clust <- factor(cluster4,levels=c(2,1,3,4)) # assigning clusters to sequences, and setting the order

df %>% 
  ggplot() +
  geom_tile(aes(x=year,y=as.factor(no),fill=code),colour="#F8F8F8") +
  facet_wrap(~clust,scales="free_y",labeller=labeller(clust = as_labeller(c("2"="Adviser-turned-executive","1"="Expertise brokers","3"="Tax law specialists","4"="Talents")))) +
  theme_void() +
  theme(
    axis.text.y = element_text(face = "plain", size = 5, margin=margin(0,-10,0,0)),
    axis.text.x = element_text(face = "plain", size = 8, margin=margin(0,0,-15,0), angle = 269),
    legend.position="bottom",
    legend.margin=margin(25,0,20,0),
    strip.text=element_text(vjust=5,face="bold",size=12,margin=margin(15,0,0,0))) +
  scale_x_continuous(breaks=1985:2014) +
  scale_fill_manual(values=cpalp, guide = "none")
  
# figure 4

df %>% 
  ggplot() +
  geom_tile(aes(x=year,y=as.factor(no),fill=code),colour="#F8F8F8") +
  facet_wrap(~clust,scales="free_y",labeller=labeller(clust = as_labeller(c("2"="Adviser-turned-executive","1"="Expertise brokers","3"="Tax law specialists","4"="Talents")))) +
  theme_void() +
  theme(
    axis.text.y = element_text(face = "plain", size = 5, margin=margin(0,-10,0,0)),
    axis.text.x = element_text(face = "plain", size = 8, margin=margin(0,0,-15,0), angle = 269),
    legend.position="bottom",
    legend.margin=margin(25,0,20,0),
    strip.text=element_text(vjust=5,face="bold",size=12,margin=margin(15,0,0,0))) +
  scale_x_continuous(breaks=1985:2014) +
  scale_fill_manual(values=cpalr, guide = "none")
  
